sudo: false
language: node_js
node_js:
  - "6.6.0"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run deploy:dev
  - npm run deploy:prod

after_success:
  - npm run codecov
